[programs.devnet]
yojimbo_token  = "6Ncnr6PZ56bZttPL9bW6FHRgwAK3ZxTCAvp8BbxvryHE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "./wallet_keypair.json"
